---
- name: Copy SSH public key to servers
  hosts: all #you can give your server group name from invetory
  gather_facts: no #fast run
  tasks:
    - name: Copy SSH public key
      authorized_key:
        user: your_remote_username
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}" #ensure correct path of your public key 
